[package]
name = "rust-enhancd"
version = "0.1.0"
authors = ["Patrick Chan <patrickchan1999@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
regex = "1"
rustc-hash = "1.0"
serde = "1.0"
serde_yaml = "0.8"